name: SAST Analysis

on:
  pull_request:
    branches:
      - prod

jobs:
  filter-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          json: true

      # - name: Checkout prod branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: prod
      #     path: prod_branch

      - name: Keep only modified files and composer.json
        run: |
          # Obtener la lista de archivos modificados
          CHANGED_FILES_JSON='${{ steps.changed-files.outputs.all_changed_files }}'
          echo "$CHANGED_FILES_JSON"
      
          # Validar que no esté vacío
          if [[ -z "$CHANGED_FILES_JSON" || "$CHANGED_FILES_JSON" == "[]" ]]; then
            echo "No se encontraron archivos modificados."
            exit 1  # Detener el proceso si no hay archivos modificados
          fi
      
          FILES_TO_KEEP=()
      
          # Agregar archivos modificados a la lista
          while IFS= read -r file; do
            FILES_TO_KEEP+=("$file")
          done < <(echo "$CHANGED_FILES_JSON" | jq -r '.[]' 2>/dev/null || echo "")
      
          # Incluir archivos específicos que siempre deben conservarse
          EXTRA_FILES=("composer.json")
          for FILE in "${EXTRA_FILES[@]}"; do
            if [ -f "$FILE" ]; then
              FILES_TO_KEEP+=("$FILE")
            fi
          done
      
          # Crear un archivo temporal con la lista de archivos a conservar
          printf "%s\n" "${FILES_TO_KEEP[@]}" > keep_files.txt
          grep -vFf keep_files.txt
      
          # Eliminar todo excepto los archivos que deben conservarse
          find . -type f -not -path "./.git/*" -print | grep -vFf keep_files.txt | xargs rm -f || echo "\nNo se elimino nada"
          # find . -type d -empty -delete  # Eliminar directorios vacíos
      
          # Eliminar la carpeta .git
          rm -rf .git
      
          # Mostrar archivos finales conservados
          echo "Archivos conservados:"
          find "$(pwd)" -type f || echo "No se conservaron archivos."
