name: Windows_IRIS_Scan

on: [push, pull_request]

env:
    IRIS_SETTINGS: ${{ secrets.IRIS_SETTINGS }}

jobs:
    scan:
        runs-on: windows-latest

        steps:
        - name: Read File
          shell: powershell
          run: |
            Get-Content -Path "(Get-Location).Path"+"\iris.settings.json"
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Install dependencies
          shell: powershell
          run: npm install
          
        - name: Create Settings File
          shell: powershell
          run: echo $IRIS_SETTINGS > iris.settings.json
          
        - name: Download IRIS Scanner CLI 
          shell: powershell
          run: Invoke-WebRequest -Uri "https://iris.codeeyesolutions.com/assets/onprem/win/v1/iris-scanner-cli.exe" -OutFile "iris-scanner-cli.exe"

        - name: Run Scan 
          shell: powershell
          run: |
            Get-Content -Path "\iris.settings.json"
            $commitId = "${{ github.sha }}"
            $shortCommitId = "PR-"+$commitId.Substring(0, 8)
            $currentDirectory = (Get-Location).Path
            .\iris-scanner-cli.exe -s $currentDirectory -r $shortCommitId